#! /bin/bash

alias guname="git config --file ~/.gitconfig.secret user.name"
alias guemail="git config --file ~/.gitconfig.secret user.email"
alias ga='git add'
alias gst='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gcmd='git commit -m "."'
alias gcl='git clone'
alias gps='git push'
alias gpl='git pull'
