#! /bin/bash

alias guname="git config --file ~/.gitconfig.secret user.name"
alias guemail="git config --file ~/.gitconfig.secret user.email"
alias ga='git add'
alias gst='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gcmd='git commit -m "."'
alias gcl='git clone'
alias gps='git push'
alias gpl='git pull'
alias gra

function gclone(){
    user=$1
    repo=$2
    if [ -z $user -o -z $repo ]; then
        echo 'Alias for git clone https://www.github.com/user/repository.git'
        echo 'Usage: gclone [user] [repository]'
    else
        git clone https://www.github.com/$user/$repo.git
    fi
}


function gra(){
    user=$1
    repo=$2
    if [ -z $user -o -z $repo ]; then
        echo 'Alias for git remote add origin git@github.com:USERNAME/REPONAME.git' 
        echo 'Usage: gra [USERNAME] [REPONAME]'
    else
        git remote add origin git@github.com:$1/$2.git
    fi
}
