#! /bin/bash

# backup existing dotfiles. 
# (buo : back-up-original)
function buo(){
    backup_dir="$HOME/dotfiles_backup"
    for name in "$@"; do
        path="$HOME/$name"
        if [ -f $path ] || [ -h $path ] || [ -d $path ];
        then
            mkdir -p $backup_dir
            new_path="$backup_dir/$name"
            printf "Found '$path'. Backing up to '$new_path\n"
            mv $path $new_path
        fi
    done
}

# visdom
alias vis='python -m visdom.server'

# jupyter notebook
alias jn='jupyter notebook'
alias jna='jupyter notebook --ip 0.0.0.0'

# gpu
alias gpu="watch --color -n.5 gpustat --color"
alias gpusmi="watch -n.5 nvidia-smi"
function usegpu(){
    if [ ! -z "$1" ]; then
        export CUDA_VISIBLE_DEVICES=$1
    else
        export CUDA_VISIBLE_DEVICES=''
    fi
}
alias ug='usegpu'

function gdown(){
    # usage: gdown [id] [name]
    CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$1" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=$1" -O $2
    rm -rf /tmp/cookies.txt
}

alias du='du -hd 1'
alias cudav='nvcc --version'
alias cudnnv='cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2'
alias jnlist='jupyter notebook list'
alias tblist='ps -ef | grep "tensorboard"'
alias pylist='ps -ef | grep "python"'

# Temp
alias pth='sa pth && pip install pandas pyyaml tqdm ipdb pdbpp tensorboard==1.14'
alias tb='sa tb && pip install tensorboard==1.12 && tensorboard --port 6006 --logdir=./'
alias jnaa='sa pth && jupyter-notebook --port 8888 --ip 0.0.0.0'

# custom rsync
function myrsync(){
    port=$1
    remainder=$2
    cmd="rsync -avzhe 'ssh -p ${port}' ${remainder}" 
    echo $cmd
    eval $cmd
}

function howmany(){
    function help(){
        echo 'Count the number of files with PATTERN in a specific location LOCATION'
        echo 'Usage: howmany LOCATION "PATTERN"'
        echo 'Example: howmany /path/to/your/images/ "*.jpg"'
    }
    if [ -z "$1" ]; then
        help
    elif [ -z "$2" ]; then
        help
    else
        set -o noglob
        dirname=$1
        pattern=$2
        cmd="find ${dirname} -name ${pattern} -printf '.' | wc -m"
        echo $cmd
        eval $cmd
        set -o glob
    fi
}
