#! /bin/bash

# backup existing dotfiles. 
# (buo : back-up-original)
function buo(){
    backup_dir="$HOME/dotfiles_backup"
    for name in "$@"; do
        path="$HOME/$name"
        if [ -f $path ] || [ -h $path ] || [ -d $path ];
        then
            mkdir -p $backup_dir
            new_path="$backup_dir/$name"
            printf "Found '$path'. Backing up to '$new_path\n"
            mv $path $new_path
        fi
    done
}

# visdom
alias vis='python -m visdom.server'

# jupyter notebook
alias jn='jupyter notebook'
alias jna='jupyter notebook --ip 0.0.0.0'

# gpu
alias gpu="watch --color -n.5 gpustat --color"
alias gpusmi="watch -n.5 nvidia-smi"
function usegpu(){
    if [ ! -z "$1" ]; then
        export CUDA_VISIBLE_DEVICES=$1
    else
        export CUDA_VISIBLE_DEVICES=''
    fi
}

function gdown(){
    # usage: gdown [id] [name]
    CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$1" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=$1" -O $2
    rm -rf /tmp/cookies.txt
}

alias du='du -hd 1'
alias cudav='nvcc --version'
alias cudnnv='cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2'

